Serhii2
DimaNarepeha/easyrepairsAngular pull request #60
Opened 2019-06-11 01:33 UTC by serhiylev

2019-06-11 05:45 UTC, AndriY2389 commented on src/app/app-routing.module.ts
>  import {NotFoundComponent} from './not-found/not-found.component';
import {AddPostComponent} from './portfolio/add-post/add-post.component';  you delete this one - is it OK ?

2019-06-11 08:37 UTC, DimaNarepeha requested changes

2019-06-11 08:37 UTC, DimaNarepeha commented on src/app/admin-approve-page/customer-view/customer-view.component.html
> +  </div>
Localhost will not work on heroku, man

2019-06-19 09:44 UTC, chen0899 commented on src/app/admin-approve-page/service-provider-view/service-provider-view.component.ts
> +
????

2019-06-19 09:44 UTC, chen0899 commented on src/app/favorite/favorite.component.html
> +                <a href="#"><i class="far fa-comments" aria-hidden="true"></i> {{serviceProvider.countComment}}</a>
router link, not href

2019-06-24 07:17 UTC, closed without merging